name: Code Formatting

on:
  push:
    branches:
      - '*'
  pull_request:
    types: [closed]
    branches:
      - '*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Run clang-format using DoozyX
      - name: Run clang-format
        uses: DoozyX/clang-format-lint-action@v0.18
        with:
          source: './src/lemlib ./include/lemlib'
          extensions: 'hpp,cpp'
          clangFormatVersion: 18

      # Commit changes if any
      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          if git diff --quiet; then
            echo "No changes to commit"
          else
            if [ "${{ github.event_name }}" = "pull_request" ]; then
              git commit --amend --no-edit
              git push origin +HEAD
            else
              git add .
              git commit -m "Apply clang-format"
              git push origin HEAD
            fi
          fi