name: Code Formatting

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Run clang-format using DoozyX
      - name: Run clang-format
        uses: DoozyX/clang-format-lint-action@v0.18
        with:
          source: './src/lemlib ./include/lemlib'
          extensions: 'hpp,cpp'
          clangFormatVersion: 18

      # Print git status and diff output
      - name: Print git status and diff
        run: |
          echo "Printing git status and diff"
          git status
          git diff

      # Commit changes if any
      - name: Commit changes
        env:
          EVENT_NAME: ${{ github.event_name }}
        run: |
          echo "Checking for changes to commit"
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          if git diff --quiet; then
            echo "No changes to commit"
          else
            echo "Changes detected, committing"
            git add .
            git commit -m "Apply clang-format"
            git push origin HEAD
          fi