name: format-code

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  format:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Check for changes in .cpp, .hpp, .h files in src/lemlib and include/lemlib
      id: check-file-changes
      run: |
        git fetch origin
        changed_files=$(git diff --name-only ${{ github.event.before }}..${{ github.sha }} -- 'src/lemlib/*.cpp' 'src/lemlib/*.hpp' 'src/lemlib/*.h' 'include/lemlib/*.cpp' 'include/lemlib/*.hpp' 'include/lemlib/*.h')
        if [ -z "$changed_files" ]; then
          echo "all_files=true" >> $GITHUB_ENV
        else
          echo "all_files=false" >> $GITHUB_ENV
          echo "changed_files=$changed_files" >> $GITHUB_ENV
        fi

    - name: Format code
      uses: DoozyX/clang-format-lint-action@v0.18
      with:
        clang-format-version: 18
        files: |
          ${{ env.changed_files }}
        style: file

    - name: Check for changes
      id: check-format-changes
      run: |
         git diff --exit-code -- 'src/lemlib/*.cpp' 'src/lemlib/*.hpp' 'src/lemlib/*.h' 'include/lemlib/*.cpp' 'include/lemlib/*.hpp' 'include/lemlib/*.h' || echo "changes=true" >> $GITHUB_ENV
      continue-on-error: true

    - name: Commit or amend changes
      run: |
        if [[ "${{ env.changes }}" == "true" ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            git commit -m "Automated code formatting"
          else
            git commit --amend --no-edit
          fi
          git push --force