name: format-code

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  format:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install clang-format
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format-18
        which clang-format-18

    - name: Output clang-format version
      run: clang-format-18 --version

    - name: Run clang-format
      uses: DoozyX/clang-format-lint-action@v0.18
      with:
        clang-format-version: 18
        extensions: '.cpp,.hpp,.h'
        path: |
          ./src/lemlib
          ./include/lemlib

    - name: Check for changes
      id: check-format-changes
      run: |
        git diff --exit-code || echo "::set-output name=changes::true"
      continue-on-error: true

    - name: Commit or amend changes
      run: |
        if [[ "${{ steps.check-format-changes.outputs.changes }}" == "true" ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            git commit -m "Automated code formatting"
          else
            git commit --amend --no-edit
          fi
          git push --force
        fi
