name: format-code

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  format:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Format code
      uses: DoozyX/clang-format-lint-action@v0.18
      with:
        source: './src/lemlib ./include/lemlib'
        extensions: 'hpp,cpp'
        clangFormatVersion: 18

    - name: Ammend changes
      if: github.event.pull_request.merged == true
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit --amend --no-edit
        git push origin HEAD --force

    - name: Commit changes on workflow dispatch
      if: github.event_name == 'workflow_dispatch'
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m 'Apply clang-format'
        git push origin HEAD