name: Code Formatting

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Run clang-format using DoozyX
      - name: Run clang-format
        uses: DoozyX/clang-format-lint-action@v0.18
        with:
          source: './src/lemlib ./include/lemlib'
          extensions: 'hpp,cpp' 
          clangFormatVersion: 18

      # Check if there are any changes after formatting
      - name: Check for formatting changes
        id: check-format-changes
        run: |
          git diff --exit-code || echo "changes"

      # Commit or amend changes
      - name: Commit or amend changes
        if: steps.check-format-changes.outputs.changes == 'changes'
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "GitHub Action"
          author_email: "action@github.com"
          message: |
            if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
              echo "Automated code formatting"
            else
              echo "Amended commit with formatted code"
            fi
          push: --force