name: format-code

on: [push]

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Run clang-format-lint
      uses: DoozyX/clang-format-lint-action@v0.18
      with:
        extensions: '.cpp,.hpp,.h'
        paths: |
          src/lemlib
          include/lemlib
    - name: Commit changes
      run: |
        if [[ -n "$(git status --porcelain)" ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Automated code formatting by clang-format-lint"
          git push
        else
          echo "No changes to commit."
