name: Auto Format

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run clang-format
      id: clang-format
      uses: DoozyX/clang-format-lint-action@v0.18
      with:
        source: './src/lemlib ./include/lemlib'
        extensions: 'hpp,cpp'
        clangFormatVersion: 18

    - name: Check for changes
      id: check_changes
      run: |
        git diff --exit-code || echo "::set-output name=changes::changes"
      continue-on-error: true

    - name: Commit changes
      if: steps.check_changes.outputs.changes == 'changes'
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Auto-format code using clang-format-18"
        git push