# automatically format code using clang-format when a pull request is merged or manually triggered
name: format-code

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  format:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Format code
      uses: DoozyX/clang-format-lint-action@v0.18
      with:
        source: './src/lemlib ./include/lemlib'
        extensions: 'hpp,cpp,h'
        clangFormatVersion: 18

    - name: Check for changes
      id: check-format-changes
      run: |
         git diff --exit-code -- 'src/lemlib/*.cpp' 'src/lemlib/*.hpp' 'src/lemlib/*.h' 'include/lemlib/*.cpp' 'include/lemlib/*.hpp' 'include/lemlib/*.h'
      continue-on-error: true

    - name: Set changes output
      id: set-changes-output
      run: |
        if [ -n "$(git diff --name-only 'src/lemlib/*.cpp' 'src/lemlib/*.hpp' 'src/lemlib/*.h' 'include/lemlib/*.cpp' 'include/lemlib/*.hpp' 'include/lemlib/*.h')" ]; then
          echo "::set-output name=changes::true"
        else
          echo "::set-output name=changes::false"
        fi

    - name: Commit or amend changes
      if: steps.set-changes-output.outputs.changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          git commit -m "Automated code formatting"
        else
          git commit --amend --no-edit
        fi
        git push --force