name: Code Formatting

on:
  pull_request:
    types: [closed] # Trigger when a PR is merged
  workflow_dispatch: # Allow manual dispatch of the workflow

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Run clang-format using DoozyX
      - name: Run clang-format
        uses: DoozyX/clang-format-lint-action@v0.18
        with:
          source: './src/lemlib ./include/lemlib'
          extensions: 'hpp,cpp'
          clangFormatVersion: 18

      # Check if there are any changes
      - name: Check for changes
        id: changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if git diff --quiet; then
            echo "No formatting changes required."
            echo "::set-output name=changes_made::false"
          else
            echo "Formatting changes required."
            echo "::set-output name=changes_made::true"
          fi

      # Amend the last commit if the PR is merged
      - name: Amend last commit
        if: github.event.pull_request.merged == true && steps.changes.outputs.changes_made == 'true'
        run: |
          git add .
          git commit --amend --no-edit
          git push --force

      # Commit changes for workflow dispatch
      - name: Commit changes
        if: github.event_name == 'workflow_dispatch' && steps.changes.outputs.changes_made == 'true'
        run: |
          git add .
          git commit -m "Apply clang-format changes"
          git push
