# Automatically format code using clang-format when a pull request is merged or manually triggered
name: format-code

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  format:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Set up clang-format using DoozyX/clang-format-lint-action@v0.18
    - name: Install and setup clang-format-18
      uses: DoozyX/clang-format-lint-action@v0.18
      with:
        clang-version: 18

    - name: Output clang-format version
      run: clang-format --version

    # Check all files in src/lemlib and include/lemlib for changes
    - name: Check for changes in .cpp, .hpp, .h files in src/lemlib and include/lemlib
      id: check-file-changes
      run: |
        git fetch origin
        changed_files=$(git diff --name-only ${{ github.event.before }}..${{ github.sha }} -- 'src/lemlib/*.cpp' 'src/lemlib/*.hpp' 'src/lemlib/*.h' 'include/lemlib/*.cpp' 'include/lemlib/*.hpp' 'include/lemlib/*.h')
        if [ -z "$changed_files" ]; then
          echo "::set-output name=all_files::true"
        else
          echo "::set-output name=all_files::false"
          echo "::set-output name=changed_files::$changed_files"
        fi

    # Format changed files. If no files are changed, then check the whole directory
    - name: Format code
      run: |
        if [ "${{ steps.check-file-changes.outputs.all_files }}" == "true" ]; then
          echo "No .cpp, .hpp, or .h files were changed in the last commit in src/lemlib and include/lemlib. Formatting all .cpp, .hpp, and .h files in these directories."
          find ./src/lemlib ./include/lemlib -name '*.cpp' -or -name '*.hpp' -or -name '*.h' | while read filename; do
            clang-format -i $filename
          done
        else
          echo "${{ steps.check-file-changes.outputs.changed_files }}" | while read filename; do
            if [[ $filename == *.cpp || $filename == *.hpp || $filename == *.h ]]; then
              clang-format -i $filename
            fi
          done
        fi

    # Check for changes after formatting
    - name: Check for changes
      id: check-format-changes
      run: |
        git diff --exit-code -- 'src/lemlib/*.cpp' 'src/lemlib/*.hpp' 'src/lemlib/*.h' 'include/lemlib/*.cpp' 'include/lemlib/*.hpp' 'include/lemlib/*.h' || echo "::set-output name=changes::true"
      continue-on-error: true

    # If a PR is merged, amend the last commit with the formatted code. If manually triggered, commit the changes
    - name: Commit or amend changes
      run: |
        if [[ "${{ steps.check-format-changes.outputs.changes }}" == "true" ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            git commit -m "Automated code formatting"
          else
            git commit --amend --no-edit
          fi
          git push --force
        fi
