name: format-code

on: [push]

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Get current date and week number
      id: date
      run: |
          echo "::set-output name=date::$(date +'%Y-%m-%d')"
          echo "::set-output name=week::$(($(date +'%U') / 2))"

    - name: Check for changes in .cpp, .hpp, .h files in src/lemlib and include/lemlib
      id: check-file-changes
      run: |
        git fetch origin
        changed_files=$(git diff --name-only ${{ github.event.before }}..${{ github.sha }} -- 'src/lemlib/*.cpp' 'src/lemlib/*.hpp' 'src/lemlib/*.h' 'include/lemlib/*.cpp' 'include/lemlib/*.hpp' 'include/lemlib/*.h')
        if [ -z "$changed_files" ]; then
          echo "::set-output name=all_files::true"
        else
          echo "::set-output name=all_files::false"
          echo "::set-output name=changed_files::$changed_files"
        fi

    - name: Format code
      uses: DoozyX/clang-format-lint-action@v0.18
      with:
        files: |
          src/lemlib/**/*.cpp
          src/lemlib/**/*.hpp
          src/lemlib/**/*.h
          include/lemlib/**/*.cpp
          include/lemlib/**/*.hpp
          include/lemlib/**/*.h

    - name: Check for changes
      id: check-format-changes
      run: |
         git diff --exit-code -- 'src/lemlib/*.cpp' 'src/lemlib/*.hpp' 'src/lemlib/*.h' 'include/lemlib/*.cpp' 'include/lemlib/*.hpp' 'include/lemlib/*.h' || echo "::set-output name=changes::true"
      continue-on-error: true

    - name: Commit changes
      run: |
        if [[ "${{ steps.check-format-changes.outputs.changes }}" == "true" ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Automated code formatting"
          git push
        fi