name: format-code

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  format:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Format code
      uses: DoozyX/clang-format-lint-action@v0.18
      with:
        source: './src/lemlib ./include/lemlib'
        extensions: 'hpp,cpp'
        clangFormatVersion: 18
        inplace: true

    - name: Commit or amend changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: GitHub Action
        author_email: action@github.com
        message: |
          ${{ github.event_name == 'workflow_dispatch' && 'Automated code formatting' || 'Amended code formatting' }}
        push: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}