name: format-code

on:
  push:
    branches:
      - '*'
  pull_request:
    types: [closed]
    branches:
      - '*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Check and format code
      id: check-and-format
      run: |
        git fetch origin
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          base_ref="HEAD^"
        else
          base_ref="${{ github.event.before }}"
        fi
        changed_files=$(git diff --name-only $base_ref..${{ github.sha }} -- 'src/lemlib/*.cpp' 'src/lemlib/*.hpp' 'src/lemlib/*.h' 'include/lemlib/*.cpp' 'include/lemlib/*.hpp' 'include/lemlib/*.h')
        if [ -z "$changed_files" ]; then
          echo "::set-output name=all_files::true"
        else
          echo "::set-output name=all_files::false"
          echo "::set-output name=changed_files::$changed_files"
          clang-format -i $changed_files
        fi

    - name: Check for format changes
      id: check-format-changes
      run: |
        git diff --exit-code -- 'src/lemlib/*.cpp' 'src/lemlib/*.hpp' 'src/lemlib/*.h' 'include/lemlib/*.cpp' 'include/lemlib/*.hpp' 'include/lemlib/*.h' || echo "::set-output name=changes::true"
        echo "::set-output name=changes::false"
      continue-on-error: true

    - name: Output format changes
      if: steps.check-format-changes.outputs.changes == 'true'
      run: git diff -- 'src/lemlib/*.cpp' 'src/lemlib/*.hpp' 'src/lemlib/*.h' 'include/lemlib/*.cpp' 'include/lemlib/*.hpp' 'include/lemlib/*.h'

    - name: Commit changes
      if: steps.check-format-changes.outputs.changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          git commit -m "Automated code formatting"
        else
          git commit --amend --no-edit
        fi
        git push --force